name: pivot
channels:
- conda-forge
dependencies:
- keras
- numpy
- scikit-learn
- theano
- matplotlib
- ipython
- h5py
- mkl-service
- notebook
- jupyterlab
- pip:
  - jupyterlab_latex
  - git+https://github.com/diana-hep/carl.git

